SSchool/SSchool/Models/Level.cs
using System.ComponentModel.DataAnnotations;

namespace SSchool.Models
{
    public class Level
    {
        public int Id { get; set; }
        [Required(ErrorMessage = " Name  Requied")]
        [UniqueNameAttribute]
        public string Name { get; set; }

        public virtual List<Student> Students { get; set; }
        public virtual List<TeachLevel> teachLevels { get; set; }
        public virtual List<Subject> subjects { get; set; }

    }
}

SSchool/SSchool/Controllers/LevelController.cs
using Microsoft.AspNetCore.Mvc;
using SSchool.Models;
using SSchool.Repository;

namespace SSchool.Controllers
{
    public class LevelController : Controller
    {
        // Context con = new Context();

        //ITeacherRepository TeacherRepository;//Tigh Couple ==>lossly couple
        ILevelRepository LevelRepository;

        //DI
        public LevelController(ILevelRepository _LevelRepo)
        {

            LevelRepository = _LevelRepo;//new LevelRepository();

        }
        public IActionResult Index()
        {
            ViewData["levelStud"] = LevelRepository.GtSTUDlevl();
            ViewData["levelsubj"] = LevelRepository.Getsubjlevl();
            return View();
        }

        public IActionResult Details(int id)
        {
            Level level = LevelRepository.GetById(id);

            return View("Details", level);

        }  
        
       
            
    }
} 

SSchool/SSchool/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SSchool.Models;
using SSchool.Repository;
using SSchool.ViewModel;
using System.Security.Claims;

namespace SSchool.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        // Context con = new Context();
        //DIP
        IStudentRepository StudentRepository;//Tigh Couple ==>lossly couple
        ILevelRepository LevelRepository;
        ISubResultRepository SubResultRepository;
        ISubjectRepository SubjectRepository;



        //DI
        public StudentController(IStudentRepository _StdRepo, ILevelRepository _LevelRepo, ISubResultRepository subRepo, ISubjectRepository subjectRepo)
        {
            StudentRepository = _StdRepo;//new StudentMockREspotory();
            LevelRepository = _LevelRepo;//new LevelRepository();
            SubResultRepository = subRepo;
            SubjectRepository = subjectRepo;
        }

        public IActionResult TestService()
        {
            ViewBag.servicesID = StudentRepository.id;
            return View();
        }


        [Route("School/{level}/{name}")]
        public IActionResult TestRoute(string name, string level)
        {
            return Content($"Ok {name} {level}");
        }

        public IActionResult CheckName(string Name, string Address)
        {
            if (Name.Contains("School"))
                return Json(true);
            return Json(false);
        }

        public IActionResult New()
        {
            ViewData["LevelList"] = LevelRepository.GetAll();//context.Departments.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]//intenal calling only "FRom the same domain
        public IActionResult SaveNew(Student stud)
        {
            // if ( stud.Name != null)
            if (ModelState.IsValid == true)
            {
                //Custom Valuation dept_Id!=0
                if (stud.level_id != 0)
                {
                    try
                    {
                        //save
                        StudentRepository.Insert(stud);
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex.Message);
                    }
                }
                else
                {
                    //error message send view 
                    ModelState.AddModelError("", "Select Level");//div
                }
            }
            ViewData["LevelList"] = LevelRepository.GetAll();//context.Levels.ToList();
                                                             //return View("New", stud);
            return View(stud);

        }


        public IActionResult Edit(int id)
        {
            Student student = StudentRepository.GetById(id);//con.Students.FirstOrDefault(s=>s.Id == id);//Model
            ViewData["LevelList"] = LevelRepository.GetAll();//con.Levels.ToList();
            return View(student);
        }

        [HttpPost]
        public IActionResult SaveEdit(int id, Student stud)
        {

            // if (newStd.Name!=null&& newStd.Age > 10 )
            if (ModelState.IsValid == true)
            {
                //get old object
                StudentRepository.Edit(id, stud);
                return RedirectToAction("Index");
                //save
            }
            //model 
            ViewData["LevelList"] =LevelRepository.GetAll();// con.Levels.ToList();

            return View("Edit", stud);
        }

        public IActionResult Delete(int id)
        {
            Student std = StudentRepository.GetById(id); //context.Students.FirstOrDefault(s => s.Id == id);
            return View(std);

        }

        public IActionResult ConfirmDelete(int id)
        {
            StudentRepository.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Student std = StudentRepository.GetById(id);//context.Students.FirstOrDefault(s => s.Id == id);
            return View(std);
        }

        [Authorize]
        public IActionResult Index()
        {
            string name = User.Identity.Name;

            string id =
                User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            return View(StudentRepository.GtALL());
        }


       //---------------------------------------------------------------------------------------------

        public IActionResult StudentDegree(int id)

        {
            GetStudentDegree stdViewModel = new GetStudentDegree();

            var stud = StudentRepository.GetById(id);
            SubResult subj_deg = SubResultRepository.GetById(id);
            int s = subj_deg.subject_id;
            int drgree = subj_deg.Degree;
            Subject subjdata = SubjectRepository.GetById(id);

            int mindegree = subjdata.MinDegree;
            string pass_not;

            if (drgree > mindegree)
            {
                pass_not = "pass";
                stdViewModel.Color = "green";
            }
            else
            {
                pass_not = "fail";
                stdViewModel.Color = "red";
            }
            stdViewModel.StudentId = stud.Id;
            stdViewModel.StudentName = stud.Name;
            stdViewModel.pass = pass_not;

            stdViewModel.SubjectName = subjdata.Name;

            return View(stdViewModel);

        }

    }









    }

SSchool/SSchool/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using SSchool.Models;
using SSchool.Repository;

namespace SSchool.Controllers
{
    public class SubjectController : Controller
    {
        ISubjectRepository SubjectRepository;//Tigh Couple ==>lossly couple
        ILevelRepository LevelRepository;
        // ISubjectRepository SubjectRepository;


        //DI
        public SubjectController(ISubjectRepository _SubRepo, ILevelRepository _LevelRepo)
        {
            SubjectRepository = _SubRepo;//new StudentMockREspotory();
            LevelRepository = _LevelRepo;//new LevelRepository();
                                         // ISubjectRepository = _Subjrepo; //new SubjectRepository();
        }


        public IActionResult Index()
        {
            
            return View(SubjectRepository .GetSubjectData());

        }

       

        public IActionResult Details(int id)
        {
            Subject sub = SubjectRepository.GetById(id);
            return View("Details", sub);

        }

        public IActionResult New()
        {
            ViewData["LevelList"] = LevelRepository.GetAll();
            return View(new Subject());

        }

        [HttpPost]
        public IActionResult SaveNew(Subject subb)
        {
            //if (subb.Name != null)
            //{
            //    con.Subjects.Add(subb);
            //    con.SaveChanges();
            //    return RedirectToAction("Index");

            //}
            //return View( "New",subb);

            ViewData["LevelList"] = LevelRepository.GetAll();
            if (ModelState.IsValid == true)
            {
                //save
                SubjectRepository.Insert(subb);
                return RedirectToAction("Index");
            }
            else
            {

                return View("New", subb);
            }
        }

        //min degree validation
        public IActionResult CheckDegree(int MinDegree, int Degree)
        {

            if (MinDegree < Degree)
                return Json(true);


            return Json(false);


        }


        public IActionResult Edit(int id)
        {
            Subject subbb = SubjectRepository.GetById(id);
            ViewData["LevelList"] = LevelRepository.GetAll();
            //ViewData["TeacherList"] = con.Teachers.ToList();
            return View(subbb);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEdit(int id, Subject newsub)
        {
            ViewData["LevelList"] = LevelRepository.GetAll();
            Subject oldsub = SubjectRepository.GetById(id);
            if (newsub.Name != null)
            {
                //get old object
                SubjectRepository.Edit(id, newsub);
                return RedirectToAction("Index");
                //save
            }
            //model 


            return View(newsub);
        }


        public IActionResult TestPartial(int id)
        {
            Subject subj = SubjectRepository.GetById(id);
            return PartialView("Details", subj);
        }



        public IActionResult Delete(int id)
        {
            Subject subj = SubjectRepository.GetById(id);
            return View(subj);

        }

        public IActionResult ConfrimDelete(int id)
        {
            SubjectRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SSchool/SSchool/Views/Level/Details.cshtml
@model Level
<div>
  <div class="card-body">
    <h4 class="card-title">Level_Id : @Model.Id </h4>
    <h4 class="card-title">Level_Name : @Model.Name</h4>
  </div>
</div>

SSchool/SSchool/Views/Level/Index.cshtml
@model List<Level>
@{
    ViewData["Title"] = "Index";
   Layout = "_ttLayout";
}


<h1>Levels Data </h1>

<h3>Student</h3>
<table class="table">
    <thead class="table-dark">
       <tr>       
         <th scope="col">ID</th>
         <th scope="col">Name</th>
         
         <th scope="col">Students</th>
        
        

       </tr>
    </thead>
    
    @foreach (var item in  ViewBag.levelStud )
    {
        <tbody>
         <tr>
            <td><h4>@item.Id</h4></td>
            <td><h4>@item.Name</h4></td>
            <td>
                <table>
                      <thead>
                        <tr>
                            <td><h4>Studnt Name</h4></td>

                        </tr>
                    </thead>
                @foreach(var tt in @item.Students)
                {
                  <tbody>
         <tr><td>@tt.Name</td>
             <td><a href="/Student/Details/@tt.Id" class="btn btn-success">Details</a></td>
             </tr>

                   </tbody>
                        
                    }
                    </table>
                    </td>
                   
            
         </tr>
       </tbody>
    }
</table>
<hr />

<a asp-controller="Student" asp-action="Index"  class="btn btn-primary">Student List</a>
<br />
<br />
<br />
<br />
<br />
<br />
<br/>


<h3>Subject</h3>

<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>

            <th scope="col">Subject</th>


        </tr>
    </thead>

    @foreach (var item in  ViewBag.levelsubj)
    {
        <tbody>
            <tr>
                <td><h4>@item.Id</h4></td>
                <td><h4>@item.Name</h4></td>
                <td>
                    <table>
                        <thead>
                            <tr>
                                <td><h4>Subject Name</h4></td>

                            </tr>
                        </thead>
                        @foreach (var tt in @item.subjects)
                        {
                            <tbody>
                                <tr>
                                    <td>@tt.Name</td>
                                    <td><a href="/Subject/Details/@tt.Id" class="btn btn-success">Details</a></td>
                                </tr>

                            </tbody>

                        }
                    </table>
                </td>

            </tr>
        </tbody>
    }
</table>
<hr />
<a asp-controller="Subject" asp-action="Index"  class="btn btn-primary"> Subject List</a>