SSchool/SSchool/Models/Student.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SSchool.Models
{
    public class Student
    {
        public int Id { get; set; }
        [Required(ErrorMessage = " Name  Requied")]
        [UniqueNameAttribute]
        public string Name { get; set; }
        [Required(ErrorMessage = " Address  Requied")]
        public string Address { get; set; }
        [Required]
        [RegularExpression(@"\w+\.(jpg|png)", ErrorMessage = "Image must be jpg or png")]
        public string Image { get; set; }

        [Display(Name = "Student Age")]
        [Required]
        [Range(maximum: 16, minimum: 11)]
        public int Age { get; set; }
        [Required(ErrorMessage = " Grade Required")]
        [RegularExpression(@"(A|B|C)", ErrorMessage = "Grade Must be A or B or C")]

        public string Grade { get; set; }
        [ForeignKey("level")]
        public int level_id { get; set; }

        public virtual Level level { get; set; }
        public virtual List<SubResult> subresults { get; set; }

    }
}

SSchool/SSchool/Controllers/LevelController.cs
using Microsoft.AspNetCore.Mvc;
using SSchool.Models;
using SSchool.Repository;

namespace SSchool.Controllers
{
    public class LevelController : Controller
    {
        // Context con = new Context();

        //ITeacherRepository TeacherRepository;//Tigh Couple ==>lossly couple
        ILevelRepository LevelRepository;

        //DI
        public LevelController(ILevelRepository _LevelRepo)
        {

            LevelRepository = _LevelRepo;//new LevelRepository();

        }
        public IActionResult Index()
        {
            ViewData["levelStud"] = LevelRepository.GtSTUDlevl();
            ViewData["levelsubj"] = LevelRepository.Getsubjlevl();
            return View();
        }

        public IActionResult Details(int id)
        {
            Level level = LevelRepository.GetById(id);

            return View("Details", level);

        }  
        
       
            
    }
} 

SSchool/SSchool/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SSchool.Models;
using SSchool.Repository;
using SSchool.ViewModel;
using System.Security.Claims;

namespace SSchool.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        // Context con = new Context();
        //DIP
        IStudentRepository StudentRepository;//Tigh Couple ==>lossly couple
        ILevelRepository LevelRepository;
        ISubResultRepository SubResultRepository;
        ISubjectRepository SubjectRepository;



        //DI
        public StudentController(IStudentRepository _StdRepo, ILevelRepository _LevelRepo, ISubResultRepository subRepo, ISubjectRepository subjectRepo)
        {
            StudentRepository = _StdRepo;//new StudentMockREspotory();
            LevelRepository = _LevelRepo;//new LevelRepository();
            SubResultRepository = subRepo;
            SubjectRepository = subjectRepo;
        }

        public IActionResult TestService()
        {
            ViewBag.servicesID = StudentRepository.id;
            return View();
        }


        [Route("School/{level}/{name}")]
        public IActionResult TestRoute(string name, string level)
        {
            return Content($"Ok {name} {level}");
        }

        public IActionResult CheckName(string Name, string Address)
        {
            if (Name.Contains("School"))
                return Json(true);
            return Json(false);
        }

        public IActionResult New()
        {
            ViewData["LevelList"] = LevelRepository.GetAll();//context.Departments.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]//intenal calling only "FRom the same domain
        public IActionResult SaveNew(Student stud)
        {
            // if ( stud.Name != null)
            if (ModelState.IsValid == true)
            {
                //Custom Valuation dept_Id!=0
                if (stud.level_id != 0)
                {
                    try
                    {
                        //save
                        StudentRepository.Insert(stud);
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex.Message);
                    }
                }
                else
                {
                    //error message send view 
                    ModelState.AddModelError("", "Select Level");//div
                }
            }
            ViewData["LevelList"] = LevelRepository.GetAll();//context.Levels.ToList();
                                                             //return View("New", stud);
            return View(stud);

        }


        public IActionResult Edit(int id)
        {
            Student student = StudentRepository.GetById(id);//con.Students.FirstOrDefault(s=>s.Id == id);//Model
            ViewData["LevelList"] = LevelRepository.GetAll();//con.Levels.ToList();
            return View(student);
        }

        [HttpPost]
        public IActionResult SaveEdit(int id, Student stud)
        {

            // if (newStd.Name!=null&& newStd.Age > 10 )
            if (ModelState.IsValid == true)
            {
                //get old object
                StudentRepository.Edit(id, stud);
                return RedirectToAction("Index");
                //save
            }
            //model 
            ViewData["LevelList"] =LevelRepository.GetAll();// con.Levels.ToList();

            return View("Edit", stud);
        }

        public IActionResult Delete(int id)
        {
            Student std = StudentRepository.GetById(id); //context.Students.FirstOrDefault(s => s.Id == id);
            return View(std);

        }

        public IActionResult ConfirmDelete(int id)
        {
            StudentRepository.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            Student std = StudentRepository.GetById(id);//context.Students.FirstOrDefault(s => s.Id == id);
            return View(std);
        }

        [Authorize]
        public IActionResult Index()
        {
            string name = User.Identity.Name;

            string id =
                User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;
            return View(StudentRepository.GtALL());
        }


       //---------------------------------------------------------------------------------------------

        public IActionResult StudentDegree(int id)

        {
            GetStudentDegree stdViewModel = new GetStudentDegree();

            var stud = StudentRepository.GetById(id);
            SubResult subj_deg = SubResultRepository.GetById(id);
            int s = subj_deg.subject_id;
            int drgree = subj_deg.Degree;
            Subject subjdata = SubjectRepository.GetById(id);

            int mindegree = subjdata.MinDegree;
            string pass_not;

            if (drgree > mindegree)
            {
                pass_not = "pass";
                stdViewModel.Color = "green";
            }
            else
            {
                pass_not = "fail";
                stdViewModel.Color = "red";
            }
            stdViewModel.StudentId = stud.Id;
            stdViewModel.StudentName = stud.Name;
            stdViewModel.pass = pass_not;

            stdViewModel.SubjectName = subjdata.Name;

            return View(stdViewModel);

        }

    }









    }

SSchool/SSchool/Views/Student/Delete.cshtml
@model Student
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div class="card" style="width:400px">
  <img class="card-img-top" src="/Images/@Model.Image" alt="Card image">
  <div class="card-body">

     <h2 class="card-title"> Name: @Model.Name</h2>
     
     <h4 class="card-text"> ID: @Model.Id</h4>
     
     <h4 class="card-text">Age: @Model.Age</h4>

     <h4 class="card-text"> Address: @Model.Address</h4>
  
     <h4 class="card-text">Grade: @Model.Grade</h4>

     <a href="/Student/ConfrimDelete/@Model.Id" class="btn btn-success">ConfrimDelete</a>

     <a href="/Student/Index" class="btn btn-primary">Back To List</a> 
  </div>
</div>

SSchool/SSchool/Views/Student/Details.cshtml
 
@model Student


<div class="card" style="width:400px">
  <img class="card-img-top" src="/Images/@Model.Image" alt="Card image">
  <div class="card-body">

    <h2 class="card-title"> Name: @Model.Name</h2>
     
     <h4 class="card-text"> ID: @Model.Id</h4>
     
     <h4 class="card-text">Age: @Model.Age</h4>

    <h4 class="card-text"> Address: @Model.Address</h4>
  

    <h4 class="card-text">Grade: @Model.Grade</h4>

    <a href="/Student/Delete/@Model.Id" class="btn btn-success">Delete</a>

     <a href="/Student/Index" class="btn btn-primary">Back To List</a>


   
  </div>
</div>

SSchool/SSchool/Views/Student/Edit.cshtml
@model Student

@{
//    Layout = "_Layout";
    ViewData["Title"] = "Edit";
    SelectList levelItems = 
            new SelectList(ViewBag.LevelList,"Id","Name");
}

<h1>Edit</h1>
<form method="post" asp-action="SaveEdit" asp-controller="Student" asp-route-id="@Model.Id">
    <div asp-validation-summary="All" class="text-danger"></div>     <div>
     
       <label asp-for="Name"></label>
       <input asp-for="Name" class="form-control" />
       
    </div>
  <div>
        <label>Address</label>
        <input asp-for="Address" class="form-control"/>
    </div>

     <div>
        <label asp-for="Age"></label>
        <input asp-for="Age" class="form-control" />
    </div>

    <div>
        <label asp-for="Image"></label>
        <input asp-for="Image"  class="form-control" />
       
    </div>

     <div>
        <label asp-for="Grade"></label>
        <input asp-for="Grade"  class="form-control" />
      
    </div>
  
     
        <div>
        <label asp-for="level"></label>
        <select asp-items="levelItems" asp-for="level_id"  class="form-control">
            <option value="0" >-- Select Level --</option>
        </select>
        <span asp-validation-for="level" class="text-danger"></span>
    </div>
    
    <input type="submit" class="btn btn-primary" value="Save" />
</form>

SSchool/SSchool/Views/Student/Index.cshtml
@model List<Student>

@{
    ViewData["Title"] = "Index";
    Layout = "_MyLayout";
}
<h1>Student Data</h1>


<a asp-controller="Student" asp-action="New"  class="btn btn-primary">New Student</a>
<hr />


<table class="table table-bordered">
     <tr>
         
         <th>Name</th>
        <th>Address</th>
        <th>Image</th>
         <th>Age</th>
          <th>Grade</th>
        


        <th>Level Name</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Address</td>
            <td>@item.Image</td>
            <td>@item.Age</td>
             <td>@item.Grade</td>
           
            <td>@item.level.Name</td>
            <td><a href="/Student/Edit/@item.Id"  class="btn btn-primary" >Edit</a></td>
            <td><a href="/Student/Delete/@item.Id"  class="btn btn-danger">Delete</a></td>
             <td><a href="/Student/Details/@item.Id"  class="btn btn-primary">Details</a></td>
             <td><a href="/Student/StudentDegree/@item.Id"  class="btn btn-primary">Student Degree</a></td>
        </tr>
    }
</table>
<br />
<br />


<a asp-controller="Level" asp-action="Index"  class="btn btn-primary">Level List</a>

SSchool/SSchool/Views/Student/New.cshtml
@model Student
@{
    ViewData["Title"] = "New";
    SelectList levelItems = new SelectList(ViewBag.LevelList,"Id","Name");
}

<h1>New</h1>
<form method="post" asp-action="SaveNew" asp-controller="Student" > @*asp-route-id="@Model.Id"*@
    <div asp-validation-summary="All" class="text-danger"></div>

    <div>
       <label asp-for="Name"></label>
       <input  asp-for="Name" class="form-control" /> 
       <span asp-validation-for="Name" class="text-danger"></span>
       
    </div>
  <div>
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
  <div>
        <label asp-for="Age"></label>
        <input asp-for="Age" class="form-control" />
        <span asp-validation-for="Age" class="text-danger"></span>
        
    </div>
    <div>
        <label asp-for="Image"></label>
        <input asp-for="Image"  class="form-control" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>

     <div>
        <label asp-for="Grade"></label>
        <input asp-for="Grade"  class="form-control" />
        <span asp-validation-for="Grade" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="level"></label>
        <select asp-items="levelItems" asp-for="level_id"  class="form-control">
            <option value="0" >-- Select Level --</option>
        </select>
        <span asp-validation-for="level_id" class="text-danger"></span>
    </div>
    <input type="submit" value="Create" class="btn btn-success" />
</form>
@section Scripts{
@*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

SSchool/SSchool/Views/Student/StudentDegree.cshtml
@{
    ViewData["Title"] = "StudentDegree";
}
@using SSchool.ViewModel;
@model GetStudentDegree;
<h1>StudentDegree</h1>
<table class="table table-borderd table-hover">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Subjest Name</th>
        <th>Pass OR Fail</th>

    </tr>
    <tr>
        <td>@Model.StudentId</td>
        <td>@Model.StudentName</td>
        <td>@Model.SubjectName</td>
        <td><h1 style="color:@Model.Color">@Model.pass</h1></td>
    </tr>
</table>